spring.application.name=crm-system

spring.datasource.url=jdbc:postgresql://localhost:5432/crm_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

logging.level.org.jdbi=DEBUG