DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS sellers;

CREATE TABLE sellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_info VARCHAR(255),
    registration_date TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT REFERENCES sellers(id),
    amount DOUBLE PRECISION NOT NULL,
    payment_type VARCHAR(50) NOT NULL,
    transaction_date TIMESTAMP NOT NULL
);